import math


WIDTH = 800
HEIGHT = 600
MAX_DISTANCE = math.hypot(WIDTH, HEIGHT)
MAX_FRAMES = 5000

INITIAL_MINERAL_COUNT = 5
INITIAL_ASTEROID_COUNT = 8
MINERAL_REFILL_THRESHOLD = 3
MINERAL_REFILL_COUNT = 2

TURN_RATE = 0.1
THRUST_THRESHOLD = 0.5
MINE_THRESHOLD = 0.5
MINING_REFUEL_AMOUNT = 10.0

EXPECTED_INPUTS = 13
EXPECTED_OUTPUTS = 3
DEFAULT_GENERATIONS = 10

ASTEROID_DANGER_MARGIN = 15
MINERAL_APPROACH_WEIGHT = 15.0
MINERAL_PROGRESS_WEIGHT = 8.0
MINERAL_ALIGNMENT_WEIGHT = 0.03
MINERAL_VELOCITY_WEIGHT = 2.0
FUEL_EFFICIENCY_WEIGHT = 5.0
REMAINING_FUEL_WEIGHT = 0.5
ASTEROID_DANGER_WEIGHT = 3.0
IDLE_PENALTY_WEIGHT = 0.02
TIME_WASTED_WEIGHT = 0.03
ASTEROID_COLLISION_PENALTY = 25.0
OUT_OF_FUEL_PENALTY = 25.0
