import math


WIDTH = 800
HEIGHT = 600
MAX_DISTANCE = math.hypot(WIDTH, HEIGHT)
MAX_FRAMES = 5000

INITIAL_MINERAL_COUNT = 5
INITIAL_ASTEROID_COUNT = 8
MINERAL_REFILL_THRESHOLD = 3
MINERAL_REFILL_COUNT = 2

TURN_RATE = 0.1
THRUST_THRESHOLD = 0.5
MINE_THRESHOLD = 0.5
MINING_REFUEL_AMOUNT = 10.0

EXPECTED_INPUTS = 13
EXPECTED_OUTPUTS = 3
DEFAULT_GENERATIONS = 500

# Starting weights for the fitness function
MINERAL_ALIGNMENT_WEIGHT = 10.0
MINERAL_VELOCITY_WEIGHT = 0.5
MINERAL_APPROACH_WEIGHT = 0.3
MINERAL_PROGRESS_WEIGHT = 0.25

ASTEROID_DANGER_MARGIN = 20
ASTEROID_DANGER_WEIGHT = 50.0
ASTEROID_COLLISION_PENALTY = 0.20
ASTEROID_COLLISION_EARLY_DEATH_WEIGHT = 10.0

WASTED_MINES_WEIGHT = 0.0
FUEL_EFFICIENCY_WEIGHT = 0.005
REMAINING_FUEL_WEIGHT = 0.0001
IDLE_PENALTY_WEIGHT = 0.0001
OUT_OF_FUEL_PENALTY = 300

TEST_SCORE_WEIGHT = 100.00
